### ISSUE TITLE
Problem with disabling sidebar.

### ISSUE THREAD

**Issue by tajwarhq** [ChapelR/harlowe-audio#10]
In Story Javascript page:
`controls : {
    show : false,`

instead of true

Returns:

There is a problem with this story's script (#1):
Cannot read property 'UpdateVolume' of undefined

Everything seems to run as normal, and sidebar is in fact removed. Just curious as to why this appears and what can be done about it.

**Comment by ChapelR** [comment]
This should have been fixed as of v1.1.2. Are you up to date?

**Comment by ChapelR** [comment]
I'm going to close this due to inactivity, but I'll reopen it if you get back to me. I'll check the controls again soon to make sure they work on the latest version as well.
