### ISSUE TITLE
README confusion

### ISSUE THREAD

**Issue by tmedwards** [ChapelR/harlowe-audio#13]
I don't know if moving to the Web Audio API is something you're working on, however, the README currently says this:

> This library uses the Web Audio API

When it actually uses the [`HTMLMediaElement` API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) at present.

**Comment by ChapelR** [comment]
Thanks I'll fix it. No Web Audio API plans, and I decided against it pretty early, so that's probably just a pure error.
