### ISSUE TITLE
(Undefined Property Issues) Report more informative error message when an undefined track is accessed.

### ISSUE THREAD

**Issue by Meydri** [ChapelR/harlowe-audio#22]
Hi! I'm using the Twine 2 app and have the latest version installed. I installed the latest version of HAL and it seems to be installed correctly (as a gray sidebar where you can adjust the volume and mute is available once playing the project). I've defined a track in a separate passage, following the exact naming conventions of the guide, but once I try to play it (for example with this code, obviously with the actual names of said tracks):
{
(track: 'track-name', 'loop', true)
(track: 'track-name', 'playwhenpossible')
}

or code such as: (track: 'beep', 'play')

I get an error message once I try to run it, saying: Error in the (track:) macro: Cannot read property 'loop' of undefined.

Or 'playwhenpossible' undefined, and so on. Basically the commands do not seem to work properly?

I've tried this code in both the very first passage as well as later passages, with the same result. I'm not a programming whiz, but from what I can gather this basically means that the function hasn't been defined properly, somehow? I'm really at a loss, because it seems like implementing sound smoothly is so close yet so far away, hahah.

Worth adding is that I've also made sure to use a proper text editor so the code shouldn't be corrupt somehow?

Thank you beforehand!

**Comment by Meydri** [comment]
Worth adding is that I've also made sure to use a proper text editor so the code shouldn't be corrupt somehow?

**Comment by ChapelR** [comment]
Defining a track in a separate passage isn't enough, you must define the track: 

1) in a `startup`-tagged passage, 
2) in the `hal.tracks` special passage, or 
3) in your story JavaScript section or equivalent, after the code for HAL. 

Are you certain you defined the track in one of those three ways?

**Comment by Meydri** [comment]
> Defining a track in a separate passage isn't enough, you must define the track:
> 
> 1. in a `startup`-tagged passage,
> 2. in the `hal.tracks` special passage, or
> 3. in your story JavaScript section or equivalent, after the code for HAL.
> 
> Are you certain you defined the track in one of those three ways?

Yes, I defined it in a hal.tracks special passage!

**Comment by ChapelR** [comment]
Can you send me the file?

**Comment by Meydri** [comment]
> Can you send me the file?

Of course! I'll send a zip which includes the audio folder. The text itself inside the passages are in Swedish eheh, but the code I've referenced from HAL is all in English so hopefully it'll be understandable.

**Comment by ChapelR** [comment]
Can you tell me how to recreate the issue? Which links to click in which order?

**Comment by ChapelR** [comment]
The story JavaScript of the file you sent is empty. There don't appear to be any HAL macros or a `hal.tracks` passage

**Comment by Meydri** [comment]
> Can you tell me how to recreate the issue? Which links to click in which order?

For me, it popped up as an issue as soon as I came to a passage where I had the code implemented. The first link to click is "Knacka." It could be that it didn't update from the old file. I'll send you a new one. Sorry for the trouble. It should have a hal.tracks passage if it's correct.

**Comment by ChapelR** [comment]
The issue is capitalization.

In `hal.tracks`:
```
obstacles: ./audio/Obstacles.mp3
```
In passage:
```
{
(track: 'Obstacles', 'loop', true)
(track: 'Obstacles', 'playwhenpossible')
}
```

In passage should be:
```
{
(track: 'obstacles', 'loop', true)
(track: 'obstacles', 'playwhenpossible')
}
```

I should probably make a more directed error message for those kinds of issues.

Suggestion: I would recommend using all lowercase letters in your file names, e.g. `./audio/obstacles.mp3` instead of `./audio/Obstacles.mp3`, since some computer systems treat lowercase and uppercase letters as different and some don't.

NOTE: I removed the files from your comments so other people can't download them.

**Comment by Meydri** [comment]
> The issue is capitalization.
> 
> In `hal.tracks`:
> 
> ```
> obstacles: ./audio/Obstacles.mp3
> ```
> 
> In passage:
> 
> ```
> {
> (track: 'Obstacles', 'loop', true)
> (track: 'Obstacles', 'playwhenpossible')
> }
> ```
> 
> In passage should be:
> 
> ```
> {
> (track: 'obstacles', 'loop', true)
> (track: 'obstacles', 'playwhenpossible')
> }
> ```
> 
> I should probably make a more directed error message for those kinds of issues.
> 
> Suggestion: I would recommend using all lowercase letters in your file names, e.g. `./audio/obstacles.mp3` instead of `./audio/Obstacles.mp3`, since some computer systems treat lowercase and uppercase letters as different and some don't.
> 
> NOTE: I removed the files from your comments so other people can't download them.

Aah, I see! You're right in that I probably should stick to stricter naming conventions, I'll keep that in mind in the future. The code works fine now in that I no longer receive any error messages, but no sound will actually play despite it being unmuted... (insert various befuddled facial expressions here). Might be something dumb that I'm just not noticing, though.

Thank you so much for your help, I truly appreciate it, and I'm sorry for all the trouble.

**Comment by ChapelR** [comment]
It works for me. Remember that you're using playWhenPossible, though.

**Comment by ChapelR** [comment]
It plays for me. What browser are you using? Make sure audio is allowed in the settings.

Press `F12` to check the JavaScript console and see if anything is there.

**Comment by Meydri** [comment]
> It plays for me. What browser are you using? Make sure audio is allowed in the settings.

Hmm.. Apparently the file wasn't found, according to the JavaScript console. Oh, and I'm using Google Chrome.

**Comment by ChapelR** [comment]
The file you sent me is sound and plays.

**Comment by ChapelR** [comment]
Try this: 
...

**Comment by Meydri** [comment]
> It plays for me. What browser are you using? Make sure audio is allowed in the settings.
> 
> Press `F12` to check the JavaScript console and see if anything is there.

Aight, I tried zipping it and opening it on another computer and it works just fine on that computer lol. So weird. But I guess that's fine. Thank you for your support.

**Comment by ChapelR** [comment]
Strange. Well try going to `chrome://settings/content` and checking the **sound** setting. If that doesn't do it, I'm not sure what will, sorry.

**Comment by Meydri** [comment]
> Try this:
>...
The zip you sent me works on my laptop (the one that's struggling right now). Sound settings look clear. But I guess I'll continue using the zip you sent me hahah. Might be some weird bug, it's quite the conundrum. Either way, things have worked out. :) Thanks so much, again hahah.
