### ISSUE TITLE
Problem with story's first script

### ISSUE THREAD

**Issue by Mantispeople** [ChapelR/harlowe-audio#27]
Hello, I emailed you about a problem that has just started happening for my story.

I get this message when opening the html file in Safari:

"There is a problem with this story's 1st script:

TypeError: null is not an object (evaluating 't[1]')
s

map

eval code
eval@[native code]"

Opening it in other browsers gives slightly different messages. The story works fine but the music doesn't play. I've tried https://twinelab.net/harlowe-audio/demo/ and that works fine for me on both Firefox and Safari.

HAL was working fine for ages and this has only just come up.

It won't allow me to upload an html here so I will email that to you. If you need any other info just let me know.

Thanks for your help!

**Comment by ChapelR** [comment]
The issue is the last track in the `hal.tracks` passage is malformed. Replace it with this:

```
Mouse scream: https://static1.squarespace.com/static/558f4d48e4b03ab3a9a4a131/t/5ed21212ff1f544b3b1d3cbc/1590825493873/Hypoxia+Mouse+Scream+-+30_05_20%2C+7.56+PM.m4a/original/Hypoxia+Mouse+Scream+-+30_05_20%2C+7.56+PM.m4a
```

**Comment by Mantispeople** [comment]
Amazing thanks!!!
