### ISSUE TITLE
JavaScript Code Error when placed into Twine.

### ISSUE THREAD

**Issue by SALXAPHONE** [ChapelR/harlowe-audio#35]
Hello. I was looking to use this on one of my twine projects, but I think there are some errors with how the code is formatted since some of the code doesn't work and I get script errors.
![image](https://user-images.githubusercontent.com/31527031/116575031-493df200-a8dc-11eb-8656-b4edc1654ff8.png)
This is the error I keep receiving. Then I look into the code and notice that all code after this point stops working.
![image](https://user-images.githubusercontent.com/31527031/116575139-5fe44900-a8dc-11eb-92ca-00ef6b5a528d.png)
Then if I try to fix it, I get another code stopping here.
![image](https://user-images.githubusercontent.com/31527031/116575277-7db1ae00-a8dc-11eb-8dcb-5e5b35964203.png)
I have little to no knowledge in JavaScript so I'm unsure how to fix these problems. Any time I try to fix these errors I just create new errors.

**Comment by ChapelR** [comment]
That's just the parser giving up. Syntax highlighting on minified code is like that. The code is not broken. This sounds like an extension clashing issue to me. 

Try turning off your ad/popup blocker extensions and see if the code works then.

**Comment by ChapelR** [comment]
Closed due to lack of response.
