### ISSUE TITLE
Adding a track macro issue

### ISSUE THREAD

**Issue by sadeceunofficial** [ChapelR/harlowe-audio#39]
I tried adding a track macro in my story but the call is seen mispelled or nonexistent even if I paste javascript and stylesheet codes and have no problem with left bar section in my story
![Ekran görüntüsü 2021-05-31 100753](https://user-images.githubusercontent.com/85098453/120154047-1b5c0e00-c1f8-11eb-8417-97d8a86a694d.png)

I use twine 2.3.14 with harlow latest version in the website.

**Comment by ChapelR** [comment]
That is normal. The macros should still work in the game.

**Comment by ChapelR** [comment]
Closed due to lack of response.
