### ISSUE TITLE
Javascript Code Error

### ISSUE THREAD

**Issue by sukanya-harris** [ChapelR/harlowe-audio#41]
When I paste the js file into Twine's JS Editor
![Screenshot (107)](https://user-images.githubusercontent.com/27587986/124080328-3e0c5d00-da18-11eb-9df8-ec34d5e7d78f.png)
![Screenshot (108)](https://user-images.githubusercontent.com/27587986/124080339-41074d80-da18-11eb-97c1-d77fcdc42fd5.png)
![Screenshot (109)](https://user-images.githubusercontent.com/27587986/124080344-42387a80-da18-11eb-8aa5-7918659a9156.png)
 I get this error and most of the code is greyed out. I'm not sure what's wrong as I copied and pasted exact code

**Comment by ChapelR** [comment]
This is merely a visual bug from the code mirror syntax highlighter Twine uses. Any miified code over a certain length does this, and this is consistent with any editor that uses code mirror, so it's not really even a Twine issue. 

Syntax highlighting is unnecessary for minified code anyway, so it's not really an issue. If you're looking to hand edit the library, you probably want to rebuild it from source.
