### ISSUE TITLE
Audio Que

### ISSUE THREAD

**Issue by THXPGit** [ChapelR/harlowe-audio#55]
I've looked over the HAL bible and it seems that there is no way to 'que' a track to play. There are ways around it of course, such as setting the replacement audio as a variable and then having it run as soon as the prior ends, but that causes a code littered with (live:)s and other filler macros.

A cleaner and easier option would be having an "add to que' argument that would allow quick and clean audio queuing without a ton of excess code. Not required for function, but would be a very nice addition to HAL.

**Comment by ChapelR** [comment]
You can use a playlist to do this.
