### ISSUE TITLE
Error when not showing controls

### ISSUE THREAD

**Issue by peastman** [ChapelR/harlowe-audio#8]
If I set `controls.show` to `false`, then Twine reports an error when I try to launch the game:

```
There is a problem with this story's script (#1):

Cannot read property 'updateVolume' of undefined
```

**Comment by ChapelR** [comment]
Whoops. I'll have a release to fix that soon.

**Comment by ChapelR** [comment]
I believe [v1.1.2](https://github.com/ChapelR/harlowe-audio/releases/tag/v1.1.2) should solve a number of sneaky issues with `controls.show`. It appears to work for me now. Thanks for the heads up on it. Let me know how it goes for you.

**Comment by peastman** [comment]
That works perfectly.  Thanks!  And thanks for creating the excellent library.
